package com.sphibmvc.entities;
// Generated 5 Aug, 2014 4:49:20 PM by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BplnmPlanSetupId generated by hbm2java
 */
@Embeddable
public class BplnmPlanSetupId  implements java.io.Serializable {


     private int bplnmpsId;
     private int bplnmpsScfuId;

    public BplnmPlanSetupId() {
    }

    public BplnmPlanSetupId(int bplnmpsId, int bplnmpsScfuId) {
       this.bplnmpsId = bplnmpsId;
       this.bplnmpsScfuId = bplnmpsScfuId;
    }
   

    @Column(name="bplnmps_id", nullable=false)
    public int getBplnmpsId() {
        return this.bplnmpsId;
    }
    
    public void setBplnmpsId(int bplnmpsId) {
        this.bplnmpsId = bplnmpsId;
    }

    @Column(name="bplnmps_scfu_id", nullable=false)
    public int getBplnmpsScfuId() {
        return this.bplnmpsScfuId;
    }
    
    public void setBplnmpsScfuId(int bplnmpsScfuId) {
        this.bplnmpsScfuId = bplnmpsScfuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BplnmPlanSetupId) ) return false;
		 BplnmPlanSetupId castOther = ( BplnmPlanSetupId ) other; 
         
		 return (this.getBplnmpsId()==castOther.getBplnmpsId())
 && (this.getBplnmpsScfuId()==castOther.getBplnmpsScfuId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBplnmpsId();
         result = 37 * result + this.getBplnmpsScfuId();
         return result;
   }   


}


