package com.sphibmvc.entities;
// Generated 5 Aug, 2014 4:49:20 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BplnmPlanSetup generated by hbm2java
 */
@Entity
@Table(name="bplnm_plan_setup"
    ,catalog="spotcrow_bplan"
)
public class BplnmPlanSetup  implements java.io.Serializable {


     private BplnmPlanSetupId id;
     private String bplnmpsGuid;
     private String bplnmpsCompanyName;
     private String bplnmpsCompanyLogo;
     private Date bplnmpsFoundedDate;
     private Date bplnmpsFiscalYear;
     private Byte bplnmpsHaveSupplyChainRelation;
     private Byte bplnmpsHaveStratagicRelation;
     private Byte bplnmpsHaveProfAdvisors;
     private Byte bplnmpsHaveBoardOfAdvisors;
     private Byte bplnmpsBoardDirsMngrs;
     private Byte bplnmpsHaveIntelPropertyPatents;
     private Byte bplnmpsCatipalDebFin;
     private Integer bplnmpsUserVisits;
     private Integer bplnmpsType;
     private Byte bplnmpsGender;
     private Byte bplnmpsNdaRequired;
     private String bplnmpsNdaRules;
     private boolean bplnmpsIsImported;
     private boolean bplnmpsIsActive;
     private Date bplnmpsCreateDate;
     private Date bplnmpsLastUpdate;

    public BplnmPlanSetup() {
    }

	
    public BplnmPlanSetup(BplnmPlanSetupId id, Date bplnmpsFoundedDate, Date bplnmpsFiscalYear, String bplnmpsNdaRules, boolean bplnmpsIsImported, boolean bplnmpsIsActive, Date bplnmpsCreateDate, Date bplnmpsLastUpdate) {
        this.id = id;
        this.bplnmpsFoundedDate = bplnmpsFoundedDate;
        this.bplnmpsFiscalYear = bplnmpsFiscalYear;
        this.bplnmpsNdaRules = bplnmpsNdaRules;
        this.bplnmpsIsImported = bplnmpsIsImported;
        this.bplnmpsIsActive = bplnmpsIsActive;
        this.bplnmpsCreateDate = bplnmpsCreateDate;
        this.bplnmpsLastUpdate = bplnmpsLastUpdate;
    }
    public BplnmPlanSetup(BplnmPlanSetupId id, String bplnmpsGuid, String bplnmpsCompanyName, String bplnmpsCompanyLogo, Date bplnmpsFoundedDate, Date bplnmpsFiscalYear, Byte bplnmpsHaveSupplyChainRelation, Byte bplnmpsHaveStratagicRelation, Byte bplnmpsHaveProfAdvisors, Byte bplnmpsHaveBoardOfAdvisors, Byte bplnmpsBoardDirsMngrs, Byte bplnmpsHaveIntelPropertyPatents, Byte bplnmpsCatipalDebFin, Integer bplnmpsUserVisits, Integer bplnmpsType, Byte bplnmpsGender, Byte bplnmpsNdaRequired, String bplnmpsNdaRules, boolean bplnmpsIsImported, boolean bplnmpsIsActive, Date bplnmpsCreateDate, Date bplnmpsLastUpdate) {
       this.id = id;
       this.bplnmpsGuid = bplnmpsGuid;
       this.bplnmpsCompanyName = bplnmpsCompanyName;
       this.bplnmpsCompanyLogo = bplnmpsCompanyLogo;
       this.bplnmpsFoundedDate = bplnmpsFoundedDate;
       this.bplnmpsFiscalYear = bplnmpsFiscalYear;
       this.bplnmpsHaveSupplyChainRelation = bplnmpsHaveSupplyChainRelation;
       this.bplnmpsHaveStratagicRelation = bplnmpsHaveStratagicRelation;
       this.bplnmpsHaveProfAdvisors = bplnmpsHaveProfAdvisors;
       this.bplnmpsHaveBoardOfAdvisors = bplnmpsHaveBoardOfAdvisors;
       this.bplnmpsBoardDirsMngrs = bplnmpsBoardDirsMngrs;
       this.bplnmpsHaveIntelPropertyPatents = bplnmpsHaveIntelPropertyPatents;
       this.bplnmpsCatipalDebFin = bplnmpsCatipalDebFin;
       this.bplnmpsUserVisits = bplnmpsUserVisits;
       this.bplnmpsType = bplnmpsType;
       this.bplnmpsGender = bplnmpsGender;
       this.bplnmpsNdaRequired = bplnmpsNdaRequired;
       this.bplnmpsNdaRules = bplnmpsNdaRules;
       this.bplnmpsIsImported = bplnmpsIsImported;
       this.bplnmpsIsActive = bplnmpsIsActive;
       this.bplnmpsCreateDate = bplnmpsCreateDate;
       this.bplnmpsLastUpdate = bplnmpsLastUpdate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="bplnmpsId", column=@Column(name="bplnmps_id", nullable=false) ), 
        @AttributeOverride(name="bplnmpsScfuId", column=@Column(name="bplnmps_scfu_id", nullable=false) ) } )
    public BplnmPlanSetupId getId() {
        return this.id;
    }
    
    public void setId(BplnmPlanSetupId id) {
        this.id = id;
    }
    
    @Column(name="bplnmps_guid", length=50)
    public String getBplnmpsGuid() {
        return this.bplnmpsGuid;
    }
    
    public void setBplnmpsGuid(String bplnmpsGuid) {
        this.bplnmpsGuid = bplnmpsGuid;
    }
    
    @Column(name="bplnmps_company_name", length=250)
    public String getBplnmpsCompanyName() {
        return this.bplnmpsCompanyName;
    }
    
    public void setBplnmpsCompanyName(String bplnmpsCompanyName) {
        this.bplnmpsCompanyName = bplnmpsCompanyName;
    }
    
    @Column(name="bplnmps_company_logo", length=250)
    public String getBplnmpsCompanyLogo() {
        return this.bplnmpsCompanyLogo;
    }
    
    public void setBplnmpsCompanyLogo(String bplnmpsCompanyLogo) {
        this.bplnmpsCompanyLogo = bplnmpsCompanyLogo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="bplnmps_founded_date", nullable=false, length=10)
    public Date getBplnmpsFoundedDate() {
        return this.bplnmpsFoundedDate;
    }
    
    public void setBplnmpsFoundedDate(Date bplnmpsFoundedDate) {
        this.bplnmpsFoundedDate = bplnmpsFoundedDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="bplnmps_fiscal_year", nullable=false, length=10)
    public Date getBplnmpsFiscalYear() {
        return this.bplnmpsFiscalYear;
    }
    
    public void setBplnmpsFiscalYear(Date bplnmpsFiscalYear) {
        this.bplnmpsFiscalYear = bplnmpsFiscalYear;
    }
    
    @Column(name="bplnmps_have_supply_chain_relation")
    public Byte getBplnmpsHaveSupplyChainRelation() {
        return this.bplnmpsHaveSupplyChainRelation;
    }
    
    public void setBplnmpsHaveSupplyChainRelation(Byte bplnmpsHaveSupplyChainRelation) {
        this.bplnmpsHaveSupplyChainRelation = bplnmpsHaveSupplyChainRelation;
    }
    
    @Column(name="bplnmps_have_stratagic_relation")
    public Byte getBplnmpsHaveStratagicRelation() {
        return this.bplnmpsHaveStratagicRelation;
    }
    
    public void setBplnmpsHaveStratagicRelation(Byte bplnmpsHaveStratagicRelation) {
        this.bplnmpsHaveStratagicRelation = bplnmpsHaveStratagicRelation;
    }
    
    @Column(name="bplnmps_have_prof_advisors")
    public Byte getBplnmpsHaveProfAdvisors() {
        return this.bplnmpsHaveProfAdvisors;
    }
    
    public void setBplnmpsHaveProfAdvisors(Byte bplnmpsHaveProfAdvisors) {
        this.bplnmpsHaveProfAdvisors = bplnmpsHaveProfAdvisors;
    }
    
    @Column(name="bplnmps_have_board_of_advisors")
    public Byte getBplnmpsHaveBoardOfAdvisors() {
        return this.bplnmpsHaveBoardOfAdvisors;
    }
    
    public void setBplnmpsHaveBoardOfAdvisors(Byte bplnmpsHaveBoardOfAdvisors) {
        this.bplnmpsHaveBoardOfAdvisors = bplnmpsHaveBoardOfAdvisors;
    }
    
    @Column(name="bplnmps_board_dirs_mngrs")
    public Byte getBplnmpsBoardDirsMngrs() {
        return this.bplnmpsBoardDirsMngrs;
    }
    
    public void setBplnmpsBoardDirsMngrs(Byte bplnmpsBoardDirsMngrs) {
        this.bplnmpsBoardDirsMngrs = bplnmpsBoardDirsMngrs;
    }
    
    @Column(name="bplnmps_have_intel_property_patents")
    public Byte getBplnmpsHaveIntelPropertyPatents() {
        return this.bplnmpsHaveIntelPropertyPatents;
    }
    
    public void setBplnmpsHaveIntelPropertyPatents(Byte bplnmpsHaveIntelPropertyPatents) {
        this.bplnmpsHaveIntelPropertyPatents = bplnmpsHaveIntelPropertyPatents;
    }
    
    @Column(name="bplnmps_catipal_deb_fin")
    public Byte getBplnmpsCatipalDebFin() {
        return this.bplnmpsCatipalDebFin;
    }
    
    public void setBplnmpsCatipalDebFin(Byte bplnmpsCatipalDebFin) {
        this.bplnmpsCatipalDebFin = bplnmpsCatipalDebFin;
    }
    
    @Column(name="bplnmps_user_visits")
    public Integer getBplnmpsUserVisits() {
        return this.bplnmpsUserVisits;
    }
    
    public void setBplnmpsUserVisits(Integer bplnmpsUserVisits) {
        this.bplnmpsUserVisits = bplnmpsUserVisits;
    }
    
    @Column(name="bplnmps_type")
    public Integer getBplnmpsType() {
        return this.bplnmpsType;
    }
    
    public void setBplnmpsType(Integer bplnmpsType) {
        this.bplnmpsType = bplnmpsType;
    }
    
    @Column(name="bplnmps_gender")
    public Byte getBplnmpsGender() {
        return this.bplnmpsGender;
    }
    
    public void setBplnmpsGender(Byte bplnmpsGender) {
        this.bplnmpsGender = bplnmpsGender;
    }
    
    @Column(name="bplnmps_nda_required")
    public Byte getBplnmpsNdaRequired() {
        return this.bplnmpsNdaRequired;
    }
    
    public void setBplnmpsNdaRequired(Byte bplnmpsNdaRequired) {
        this.bplnmpsNdaRequired = bplnmpsNdaRequired;
    }
    
    @Column(name="bplnmps_nda_rules", nullable=false, length=65535)
    public String getBplnmpsNdaRules() {
        return this.bplnmpsNdaRules;
    }
    
    public void setBplnmpsNdaRules(String bplnmpsNdaRules) {
        this.bplnmpsNdaRules = bplnmpsNdaRules;
    }
    
    @Column(name="bplnmps_is_imported", nullable=false)
    public boolean isBplnmpsIsImported() {
        return this.bplnmpsIsImported;
    }
    
    public void setBplnmpsIsImported(boolean bplnmpsIsImported) {
        this.bplnmpsIsImported = bplnmpsIsImported;
    }
    
    @Column(name="bplnmps_is_active", nullable=false)
    public boolean isBplnmpsIsActive() {
        return this.bplnmpsIsActive;
    }
    
    public void setBplnmpsIsActive(boolean bplnmpsIsActive) {
        this.bplnmpsIsActive = bplnmpsIsActive;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bplnmps_create_date", nullable=false, length=19)
    public Date getBplnmpsCreateDate() {
        return this.bplnmpsCreateDate;
    }
    
    public void setBplnmpsCreateDate(Date bplnmpsCreateDate) {
        this.bplnmpsCreateDate = bplnmpsCreateDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bplnmps_last_update", nullable=false, length=19)
    public Date getBplnmpsLastUpdate() {
        return this.bplnmpsLastUpdate;
    }
    
    public void setBplnmpsLastUpdate(Date bplnmpsLastUpdate) {
        this.bplnmpsLastUpdate = bplnmpsLastUpdate;
    }




}


